name: Generate tokenlists

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Generate Tokenlists
        run: npm run generate
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          POKT_KEY: ${{ secrets.POKT_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update generated tokenlists'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-tokenlists
          delete-branch: true
          title: 'Update generated tokenlists'
          body: |
            This PR was autogenerated because of changes to tokenlists.
          draft: false
